---
title: "Scales and Axes"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
        message = T,
        error = T,
        warning = T,
        comment = '##',
        highlight = T,
        prompt = T,
        echo = T
        )
library(tidyverse)
```

## Removing all guides from a plot


```{r remove-all-guides}
ggplot(mpg, aes(displ, hwy)) +
    geom_point(aes(color = class), show.legend = FALSE) +
    labs( x = NULL, y = NULL, color = NULL) +
    scale_x_continuous(breaks = NULL) +
    scale_y_continuous(breaks = NULL)

```

```{r}
set.seed(1234)
v <- as_tibble(rnorm(10000, 10, 2.5))
ggplot(v, aes(x = value)) +
    geom_histogram(binwidth = .5,  colour = "black", fill = "white")
```


```{r}
set.seed(1234)
v <- as_tibble(rnorm(10000))
ggplot(v, aes(x = value)) +
    geom_histogram(aes(y = ..density..), bins = 40,  colour = "black", fill = "white") +
    geom_line(aes(y = ..density.., colour = 'Empirical'), stat = 'density') 
```

```{r }
x <- rnorm(1000)

p0 = qplot(x, geom = 'blank') +   
  geom_line(aes(y = ..density.., colour = 'Empirical'), stat = 'density') +  
  stat_function(fun = dnorm, aes(colour = 'Normal')) +                       
  geom_histogram(aes(y = ..density..), alpha = 0.4, bins = 40) +            
  scale_colour_manual(name = 'Density', values = c('red', 'blue')) + 
  theme(legend.position = c(0.85, 0.85))

print(p0)
```

## Histogram of a normal distribution

```{r histogram-normal-distribution}
set.seed(1234)
v <- as_tibble(rnorm(10000))
ggplot(v, aes(x = value)) +
    geom_histogram(bins = 40, colour = "black", fill = "white")
```

## Densitiy of a normal distribution

```{r density-curve-normal-distribution}
set.seed(1234)
v <- as_tibble(rnorm(10000))
ggplot(v, aes(x=value)) + geom_density()
```

```{r my-try}
library(modeest)
set.seed(1234)
v <- as_tibble(rnorm(10000, 10, 2.5))
M <- mlv(v$value, method = "discrete")[[1]]
ylab <- c(seq(from = 0, to = 800, by = 200))
Y = c(seq(
    from = 0,
    to = 0.05,
    length.out = 5
    ))
# ggplot(v, aes( x = value)) +
#     geom_histogram(bins = 40) +
#     stat_bin(bins = 40, colour = "black", fill = "white")
ggplot(v, aes(x = value)) +
    geom_histogram(aes(y = ..density..), bins = 40,  colour = "black", fill = "white") +
    geom_line(aes(y = ..density.., color = 'Empirical'), stat = 'density') +     stat_function(fun = dnorm, aes(color = 'Normal'),
                     args = list(mean = 10, sd = 2.5)) +
    scale_colour_manual(name = "Colors", values = c("red", "blue")) +
    scale_y_continuous(name = "Frequency", breaks = Y, labels = ylab)


```


```{r density-with-x-frequency}
# https://datascienceplus.com/compare-distribution-by-density-plots/

x <- seq(from = 110, to = 174, by = 0.5)
y1 <- dnorm(x, mean = 145, sd = 9)
y2 <- dnorm(x, mean = 138, sd = 8)
plot(x, y1, type="l", lwd=2, col="red",
     main="Systolic Blood Pressure Before and After Treatment",
     xlab = "Systolic Blood Pressure (mmHg)",
     ylab = "Frequency", yaxt="n",
     xlim = c(110, 175), ylim = c(0, 0.05))
lines(x, y2)
polygon(c(110,x,175),c(0,y2,0), col="firebrick3",
     border = "black")
polygon(c(117,x,175),c(0,y1,0), col="dodgerblue4",
     border = "black")
ylab=c(seq(from=0, to=175, by=25))
y=c(seq(from=0, to=0.05, length.out = 8))
axis(2,at=y,labels=ylab, las=1)
text(x = 120, y = 0.045, "- Pre-Treatment BP", col = "dodgerblue4", cex = 0.9)
text(x = 120, y = 0.04, " - Post-Treatment BP", col = "firebrick3", cex = 0.9)
points(109, 0.0445, pch = 15, col = "dodgerblue4")
points(109, 0.0395, pch = 15, col = "firebrick3")
```

```{r freqency-x-axis-with-density}

# https://datascienceplus.com/compare-distribution-by-density-plots/
# converted to ggplot

x <- seq(from = 110, to = 174, by = 0.5)
y1 <- dnorm(x, mean = 145, sd = 9)
y2 <- dnorm(x, mean = 138, sd = 8)
plot(x, y1, type="l", lwd=2, col="red",
     main="Systolic Blood Pressure Before and After Treatment",
     xlab = "Systolic Blood Pressure (mmHg)",
     ylab = "Frequency", yaxt="n",
     xlim = c(110, 175), ylim = c(0, 0.05))
lines(x, y2)
# polygon(c(110,x,175),c(0,y2,0), col="firebrick3",
#      border = "black")
# polygon(c(117,x,175),c(0,y1,0), col="dodgerblue4",
#      border = "black")
ylab=c(seq(from=0, to=175, by=10))
y=c(seq(from=0, to=0.05, length.out = 18))
axis(2,at=y,labels=ylab, las=1)
# text(x = 120, y = 0.045, "- Pre-Treatment BP", col = "dodgerblue4", cex = 0.9)
# text(x = 120, y = 0.04, " - Post-Treatment BP", col = "firebrick3", cex = 0.9)
# points(109, 0.0445, pch = 15, col = "dodgerblue4")
# points(109, 0.0395, pch = 15, col = "firebrick3")
```

```{r my-SO-question}
library(ggplot2)
set.seed(1234)
v <- as_tibble(rnorm(1000, 10, 2.5))
ggplot(v, aes(x = value)) +
    geom_histogram(aes(y = ..density..), 
                   bins = 40,  colour = "black", fill = "white") +
    geom_line(aes(y = ..density.., color = 'Empirical'), stat = 'density') +     
    stat_function(fun = dnorm, aes(color = 'Normal'),
                     args = list(mean = 10, sd = 2.5)) +
    scale_colour_manual(name = "Colors", values = c("red", "blue"))


```


```{r}
control <- c(4.17,3.05,5.18,4.01,6.11,4.1,5.17,3.57,5.33,5.59,
         4.66,5.58,3.66,4.50,3.90,4.61,5.62,4.53,6.05,5.14)
hist(control,col="gray",xlab="Utility", prob=TRUE,  ylim=c(0,0.5),
main="Histogram of individual utilities")
curve(dnorm(x,mean=mean(control),sd=sd(control)), add=TRUE,col="red")
```

```{r}
library(ggplot2)
set.seed(1234)
v <- as_tibble(rnorm(10000, 10, 2.5))
ggplot(v, aes(x = value)) +
   geom_histogram(aes(y = ..ncount..)) + 
   geom_density(aes(y = ..scaled..))
```

```{r}
df1 <- data.frame(v = rnorm(164, mean = 9, sd = 1.5))
b1  <- seq(4.5, 12, by = 0.1)
hist.1a <- ggplot(df1, aes(x = v)) +
        geom_histogram(aes(y = ..count..),
                breaks = b1,
                fill = "blue",
                color = "black") +
        geom_density(aes(y = ..density.. * (164 * 0.1)))
hist.1a
```

```{r}
library(ggplot2)
set.seed(1234)
v <- as_tibble(rnorm(1000, 10, 2.5))
b  <- seq(0, 20, by = 0.5)
p1 <- ggplot(v, aes(x = value)) +
    geom_histogram(aes(y = ..count..), 
                   breaks = b,
                   binwidth = 0.5,  
                   colour = "black", 
                   fill = "white") +
    geom_line(aes(y = ..density.. * (1000 * 0.5),
                    colour = 'Empirical'),
                    stat = 'density') +
    stat_function(fun = function(x) { 
        (dnorm(x, mean = mean, sd = sd) * 1000 * 0.5)
    }, show.legend = TRUE, colour = 'blue') 
    
    
#    geom_line(aes(y = dnorm(10000, 10, 2.5)), color = 'blue', stat = "identity") +

#    geom_density(aes(y = (dnorm(10000, 10, 2.5) * (10000 * 0.5)), color = 'Normal')) +
 
    # stat_function(fun = dnorm, aes(color = 'Normal'),
    #                  args = list(mean = 10, sd = 2.5)) +

#    stat_density(aes(dnorm(10000, 10, 2.5), color = 'Normal'), ) +

#  	stat_function(
# 		fun = function(x, mean, sd, n){
# 			n * dnorm(x = v$value, mean = 10, sd = 2.5)
# 		},
# 		args = list(mean = 10, sd = 2.5, n = length(v$value)))
p1

```

```{r histo-with-counts-and-density-axes}

#https://stackoverflow.com/questions/38557676/integrating-histogram-and-density-curve-with-one-axis-for-frequency-and-the-oth

set.seed(0)  ## added for reproducibility
g <- rnorm(2000, 5, 1)
h <- hist(g, breaks = 50, plot = FALSE)

pos <- pretty(h$density, n = 5)
freq <- round(pos * length(g) * with(h, breaks[2] - breaks[1]))
new.mai <- old.mai <- par("mai")
new.mai[4] <- old.mai[2]
par(mai = new.mai)

graphics:::plot.histogram(h, freq = FALSE, col="bisque", main="Integrated Histogram",
                          xlab = paste0("Cr","(mg/dL)"), ylab="Frequeny",
                          border="black", yaxt='n')
Axis(side = 2, at = pos, labels = freq)
Axis(side = 4, at = pos, labels = pos)
mtext("Density", side = 4, line = 3)
lines(density(g), col="dimgray")

par(mai = old.mai)
```

```{r}
ggplot(mtcars, aes(x = mpg)) + 
	geom_histogram(fill = "red") + 
	stat_function(
		fun = function(x, mean, sd, n){
			n * dnorm(x = x, mean = mean, sd = sd)
		}, 
		args = with(mtcars, c(mean = mean(mpg), sd = sd(mpg), n = length(mpg)))
	) + 
	scale_x_continuous("Miles per gallon")
```


```{r}
# https://stackoverflow.com/questions/6967664/ggplot2-histogram-with-normal-curve
# the (last) answer by PatrickT
n = 1000
mean = 10
sd = 2.5
binwidth = 0.5 # passed to geom_histogram and stat_function
set.seed(1)
df <- data.frame(x = rnorm(n, mean, sd))

ggplot(df, aes(x = x, mean = mean, sd = sd, binwidth = binwidth, n = n)) +
    theme_bw() +
    geom_histogram(binwidth = binwidth, 
        colour = "white", fill = "cornflowerblue", size = 0.1) +
stat_function(fun = function(x) dnorm(x, mean = mean, sd = sd) * n * binwidth,
    color = "darkred", size = 1)
```

```{r final-solution}
library(ggplot2)
n = 1000
mean = 10
sd = 2.5
binwidth = 0.5
set.seed(1234)
v <- as_tibble(rnorm(n, mean, sd))
b  <- seq(0, 20, by = binwidth)
ggplot(v, aes(x = value, mean = mean, sd = sd, binwidth = binwidth, n = n)) +
    geom_histogram(aes(y = ..count..), 
           breaks = b,
           binwidth = binwidth,  
           colour = "black", 
           fill = "white") +
    geom_line(aes(y = ..density.. * n * binwidth, colour = "Empirical"),
           size = 1, stat = 'density') +
    stat_function(fun = function(x) 
           {dnorm(x, mean = mean, sd = sd) * n * binwidth}, 
           aes(colour = "Normal"), size = 1) +
    labs(x = "Score", y = "Frequency") +
    scale_colour_manual(name = "Line colors", values = c("red", "blue"))
```


